### ISSUE TITLE
请教训练细节

### ISSUE THREAD

**Issue by HelloRicky123** [mozhuangb/SiameseFC-pytorch#2]
你好，请问这个是直接训练，直接测试，代码不需要改动就可以在OTB13上达到0.50+的auc吗？我现在训练到40个epoch了，看到的最大的auc是33个epoch时的0.44.

**Comment by hao-liu-china** [comment]
是的，如果需要，我可以把我的训练模型发给你。

**Comment by HelloRicky123** [comment]
嗯。。如果有时间的话求发一下，我的邮箱是qftju12345@163.com，或者其他方式都可以。
多谢帮助🙏

**Comment by hao-liu-china** [comment]
@HelloRicky123 好的，已发送
